### ISSUE TITLE
Mark flags that are not accessible

### ISSUE THREAD

**Issue by TasnSchimmerlos** [Hydroxycobalamin/dPrevention#1]
An Option to mark th flags in the flag GUI as not accessible for the player.
For example with other Icons as the normal ones.

**Comment by Hydroxycobalamin** [comment]
Added in 3ecddb0b06a7a09f3d0fafd545a99b0f43bcc00c

Set `hide-flags-permissions` to `true` and set a custom `hide-flag-item` in the config. The option will be available, when the next release build is pushed. 

Note:
Do not use development builds on live servers.
